#!/usr/bin/env lua

local olsrd = require 'gluon.olsrd'

local info = olsrd.oi()

local gateways = { }

if info.olsr2.running then
	for _, network in ipairs(olsrd.olsr2_get_nodeinfo('olsrv2info jsonraw attached_network').attached_network) do
		if network.attached_net_src == '::/0' then
			table.insert(gateways, network.node)
		end
	end
end

if info.olsr1.running then
	for _, hna in ipairs(olsrd.olsr1_get_nodeinfo('hna').hna) do
		if hna.destination == '::' then
			table.insert(gateways, hna.gateway)
		end
	end
end

if #gateways == 0 then
	os.exit(1)
end
