#!/bin/sh /etc/rc.common

# before olsrd (65)
START=64
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/olsr-macd
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}
